package com.product.inventomini.service;

import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import com.product.inventomini.entity.Order;
import com.product.inventomini.entity.Payment;
import com.product.inventomini.repository.OrderRepository;
import com.product.inventomini.repository.PaymentRepository;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.*;
import com.itextpdf.layout.*;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.*;

@Service
public class ReportService {

    private final OrderRepository orderRepo;
    private final PaymentRepository paymentRepo;

    public ReportService(OrderRepository orderRepo,
                         PaymentRepository paymentRepo) {
        this.orderRepo = orderRepo;
        this.paymentRepo = paymentRepo;
    }

    public byte[] generateReport(LocalDate fromDate, LocalDate toDate) {

        LocalDateTime from = fromDate.atStartOfDay();
        LocalDateTime to = toDate.atTime(23, 59, 59);

        List<Order> orders = orderRepo.findByOrderDateBetween(from, to);

        double totalSales = 0;
        double totalPaid = 0;

        for (Order o : orders) {
            totalSales += o.getTotalAmount();

            List<Payment> payments = paymentRepo.findByOrder(o);
            for (Payment p : payments) {
                totalPaid += p.getAmount();
            }
        }

        double balance = totalSales - totalPaid;

        long customerCount = orders.stream()
                .map(o -> o.getCustomer().getId())
                .distinct()
                .count();

        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();

            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdf = new PdfDocument(writer);
            Document doc = new Document(pdf);

            // 🔥 HEADER (COMPANY NAME)
            doc.add(new Paragraph("INVENTOMINI WHOLESALE")
                    .setBold()
                    .setFontSize(20)
                    .setTextAlignment(TextAlignment.CENTER));

            doc.add(new Paragraph("Sales Report")
                    .setTextAlignment(TextAlignment.CENTER));

            doc.add(new Paragraph("From: " + fromDate + "    To: " + toDate)
                    .setTextAlignment(TextAlignment.CENTER));

            doc.add(new Paragraph("---------------------------------------------------"));

            // 🔥 SUMMARY BOX
            Table summary = new Table(2)
                    .setWidth(UnitValue.createPercentValue(50))
                    .setMarginBottom(20);

            summary.addCell(getCell("Total Orders", true));
            summary.addCell(getCell(String.valueOf(orders.size()), false));

            summary.addCell(getCell("Customers", true));
            summary.addCell(getCell(String.valueOf(customerCount), false));

            summary.addCell(getCell("Total Sales", true));
            summary.addCell(getCell("₹" + totalSales, false));

            summary.addCell(getCell("Total Paid", true));
            summary.addCell(getCell("₹" + totalPaid, false));

            summary.addCell(getCell("Balance", true));
            summary.addCell(getCell("₹" + balance, false));

            doc.add(summary);

            // 🔥 MAIN TABLE
            Table table = new Table(UnitValue.createPercentArray(5))
                    .useAllAvailableWidth();

            // HEADER STYLE
            table.addHeaderCell(headerCell("Type"));
            table.addHeaderCell(headerCell("Order ID"));
            table.addHeaderCell(headerCell("Customer"));
            table.addHeaderCell(headerCell("Amount"));
            table.addHeaderCell(headerCell("Date"));

            // DATA
            for (Order o : orders) {

                table.addCell(normalCell("ORDER"));
                table.addCell(normalCell(String.valueOf(o.getId())));
                table.addCell(normalCell(o.getCustomer().getShopName()));
                table.addCell(normalCell("₹" + o.getTotalAmount()));
                table.addCell(normalCell(String.valueOf(o.getOrderDate())));

                List<Payment> payments = paymentRepo.findByOrder(o);

                for (Payment p : payments) {
                    table.addCell(normalCell("PAYMENT"));
                    table.addCell(normalCell(String.valueOf(o.getId())));
                    table.addCell(normalCell("-"));
                    table.addCell(normalCell("₹" + p.getAmount()));
                    table.addCell(normalCell(String.valueOf(p.getPaymentDate())));
                }
            }

            doc.add(table);

            // 🔥 FOOTER
            doc.add(new Paragraph("\nGenerated by InventoMini System")
                    .setTextAlignment(TextAlignment.RIGHT)
                    .setFontSize(10));

            doc.close();

            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("PDF Generation Error");
        }
    }

    // 🔥 HELPER METHODS

    private Cell headerCell(String text) {
        return new Cell()
                .add(new Paragraph(text).setBold())
                .setBackgroundColor(ColorConstants.LIGHT_GRAY)
                .setTextAlignment(TextAlignment.CENTER);
    }

    private Cell normalCell(String text) {
        return new Cell()
                .add(new Paragraph(text))
                .setTextAlignment(TextAlignment.CENTER);
    }

    private Cell getCell(String text, boolean bold) {
        Paragraph p = new Paragraph(text);
        if (bold) p.setBold();

        return new Cell().add(p);
    }
}